---
- name: Create base folder structure
  ansible.builtin.import_tasks: folder.yml

- name: Adjust local time
  ansible.builtin.import_tasks: localtime.yml

- name: Base repository assignment
  ansible.builtin.import_tasks: repositories.yml
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Deploy baseline packages
  ansible.builtin.import_tasks: packages.yml
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Deploy global hosts configuration
  ansible.builtin.import_tasks: hosts.yml

- name: Deploy customized message of the day
  ansible.builtin.import_tasks: motd.yml

- name: Deploy standard local firewall configuration
  ansible.builtin.import_tasks: firewall.yml

- name: Deploy user settings
  ansible.builtin.import_tasks: user.yml

- name: Deploy system activity reporter
  ansible.builtin.import_tasks: sysstat.yml
