---
- name: Installation of base packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages }}"
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8

- name: Installation of base packages (x86_64)
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages_x86_64 }}"
  when:
    - ansible_facts['architecture'] == "x86_64"
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8
