---
- name: Deploy RPM keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ role_directory }}/keys/"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - keys/RPM-GPG-KEY-*

- name: Import rpm key for THBE signed packages
  ansible.builtin.rpm_key:
    state: present
    key: "{{ role_directory }}/keys/RPM-GPG-KEY-thbe"
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Deploy local RPMs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ role_directory }}/rpms/"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - rpms/*.rpm
