---
- name: Deploy sysstat packages
  ansible.builtin.dnf:
    name:
      - sysstat
    state: present

- name: Enable and start sysstat service
  ansible.builtin.service:
    name: sysstat
    state: started
    enabled: true

- name: Enable and start sysstat-collect timer
  ansible.builtin.service:
    name: sysstat-collect.timer
    state: started
    enabled: true
